Way to much.

diff --git a/functions/save-function b/functions/save-function
--- a/functions/save-function
+++ b/functions/save-function
@@ -6,23 +6,33 @@
 #:   Saves to the last path in ^S$FPATH^s if there is no definition file
 #:     already, or overwrites the first match in ^S$FPATH^s if one exists.
 
-function save-function {
+function save-function {(
 	local fpath fname fbody fstart fend oprefix=xx i
 	: ${1:?Missing required argument function_name.}
 	: ${2:?Missing required argument help_message.}
 	: ${FPATH:?Required environment variable FPATH is not defined.}
 	[[ $1 == xx[0-9][0-9] ]]&& oprefix=XX
-	fpath="${FPATH##*:}"
+	fpath="$(readlink -fn "${FPATH%%:*}")"
+	[[ -n $fpath ]]||
+		die "^B${FPATH%%:*}^b is not in the filesystem."
+	[[ -d $fpath ]]||
+		die "^B${FPATH%%:*}^b is not a directory."
+
 	search-path "$FPATH" "$1"
-	[[ -n "${reply[0]}" ]]&& fpath="${reply[0]%*/}"
+	[[ -n "${reply[0]}" ]]&& fpath="${reply[0]%/*}"
 	fbody="$(typeset -f "$1")" || die "Function ^B$1^b is not defined."
 	[[ $fbody == "$1() " ]]&& {
 		[[ -f $fpath/$1 ]]|| die "Unknown function name: ^B$1^b."
 		. $fpath/$1
 		fbody="$(typeset -f "$1")" || die "Function ^B$1^b does not exist."
 	  }
-	cd "$(mkdir -d)" || die "Could not ^Tcd^t to temporary directory."
+	builtin cd "$(mktemp -d)" ||
+		die "Could not ^Tcd^t to temporary directory."
 	if [[ -f $fpath/$1 ]]; then
+		yes-or-no 'Function file already exists. Overwrite' || {
+			eval "cd -; rmdir \"$PWD\""
+			return
+		  }
 		cp $fpath/$1 .
 	else
 		new -n -t ksh -x function "$@"
@@ -42,6 +52,6 @@ function save-function {
 	rm *
 	eval "cd -; rmdir \"$PWD\""
 	unset reply
-}
+)}
 
 # Copyright © 2017 by Tom Davis <tom@greyshirt.net>.
