needs-path: require action, no default create
Remove -no-create in favor of -create and set no-create as the default.
Add -or-false action and require an explicit action flag instead of
	defaulting to returning false.
Require a directory path to be given. Previously an empty string was
	allowed, I don't remember why, but that seems very bad.
[syn] update all scripts and functions in BS and FS to use these new
	defaults and flags.

diff --git a/share/FS/needs-path b/share/FS/needs-path
--- a/share/FS/needs-path
+++ b/share/FS/needs-path
@@ -1,23 +1,23 @@
 # <@(#)tag:tw.csongor.greyshirt.net,2021-10-19,16.44.57z/ebcd74>
 # vim: filetype=ksh tabstop=4 textwidth=72 noexpandtab
 
-#: FUNCTION ^[^T-or-warn^t^|^T-or-die^t^] ^[^T-no-create^t^|^T-with-notice^t^] ^Udir name^u
-#:   ^Tmkdir^t if necessary unless ^T-no-create^t, possibly warn or die, optionally
+#: FUNCTION ^[^T-create^t^] ^[^T-with-notice^t^] ^T-or-false^t|^T-or-warn^t^|^T-or-die^t ^Udir name^u
+#:   ^Tmkdir^t if ^T-create^t, possibly warn or die, optionally
 #:   notifying if it is created.
 
 needs bad-programmer die notify sparkle-path warn
 function needs-path {
-	local or_what notice v r create errmsg w_warn w_die
+	local create dirname errmsg notice or_what r v
 
-	create=true
+	create=false
 	notice=false
-	w_warn=false
-	w_die=false
+	or_what=''
 	while (($#>1)); do
 		case $1 in
-			-or-warn)		w_warn=true;	or_what=warn;					;;
-			-or-die)		w_die=true;		or_what=die;					;;
-			-no-create)		create=false;									;;
+			-or-false)		or_what=${or_what:+$or_what }false;				;;
+			-or-warn)		or_what=${or_what:+$or_what }warn;				;;
+			-or-die)		or_what=${or_what:+$or_what }die;				;;
+			-create)		create=true;									;;
 			-with-notice)	notice=true;									;;
 			-*)				bad-programmer "^T$0^t: Unknown flag ^T$1^t.";	;;
 			*)				die "Too many parameters.";						;;
@@ -25,27 +25,33 @@ function needs-path {
 		shift
 	done
 	$notice && ! $create && bad-programmer \
-		'^T-no-create^t and ^T-with-notice^t are mutually exclusive.'
+		'^T-with-notice^t is only valid with ^T-create^t.'
 
-	$w_warn && $w_die && bad-programmer \
-		'^T-or-warn^t and ^T-or-die^t are mutually exclusive.'
+	[[ -n ${1:-} ]]|| die 'Missing required parameter ^Udir name^u.'
+	dirname=$1
 
-	[[ -z $1 ]]&& return
-	[[ -d $1 ]]&& return
+	[[ -n $or_what ]]|| die "Missing required ^T-or-^t^Uaction^u."
+	[[ $or_what == *\ * ]]&& {
+		set -- $or_what
+		case $# in
+			3)	errmsg="^T-or-$1^t, ^T-or-$2^t, and ^T-or-$3^t";	;;
+			2)	errmsg="^T-or-$1^t and ^T-or-$2^t";					;;
+			*)	bad-programmer "\$#: $#, or_what: '$or_what'";		;;
+		esac
+		die "There should only be one action, not $errmsg."
+	  }
 
-	sparkle-path "$1"
+	[[ -d $dirname ]]&& return
+
+	sparkle-path "$dirname"
 
 	if $create; then
 		$notice && notify "Creating directory $REPLY."
-		mkdir -p "$1" >/dev/null 2>&1 && return
-		errmsg="Could not ^Tmkdir -p^t $REPLY."
+		mkdir -p "$dirname" >/dev/null 2>&1 && return
+		errmsg="$REPLY does not exist and could not be created."
 	else
-		[[ -n ${or_what-} ]]||
-			bad-programmer "^T$0 -no-create^t requires ^T-or-^t^{^Twarn^t^,^Tdie^t^}"
 		errmsg="No such directory $REPLY."
 	fi
-
-	[[ -n ${or_what:-} ]]|| return
 
 	$or_what "$errmsg"
 }
